development:
  adapter: mysql
  database: sharelocally_development
  username: root
  password: password
  host: localhost

test:
  adapter: mysql
  database: sharelocally_test
  username: root
  password: password
  host: localhost

production:
  adapter: mysql
  database: sharelocally_production
  username: root
  password: sharel0cally
  host: localhost
