development:
  adapter: mysql
  database: sharelocally_development
  username: root
  password: password
  host: localhost

test: &TEST
  adapter: mysql
  database: sharelocally_test
  username: root
  password: password
  host: localhost

cucumber:
  <<: *TEST

selenium:
  <<: *TEST
  database: sharelocally_selenium